blueprints/qa.py
from flask import Blueprint, render_template, request, g, redirect, url_for, flash
from decorators import login_required
from .forms import QuestionForm, AnswerForm
from models import QuestionModel, AnswerModel
from exts import db
from sqlalchemy import or_

bp = Blueprint("qa", __name__, url_prefix="/")


@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(db.text("-create_time")).all()
    return render_template("index.html", questions=questions)


@bp.route("/question/public", methods=['GET', 'POST'])
@login_required
def public_question():
    if request.method == 'GET':
        return render_template("public_question.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题或内容格式错误！")
            return redirect(url_for("qa.public_question"))


@bp.route(("/question/<int:question_id>"))
def question_detail(question_id):
    question = QuestionModel.query.get(question_id)
    return render_template("detail.html", question=question)


@bp.route("/answer/<int:question_id>", methods=['POST'])
@login_required
def answer(question_id):
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        answer_model = AnswerModel(content=content, author=g.user, question_id=question_id)
        db.session.add(answer_model)
        db.session.commit()
        return redirect(url_for("qa.question_detail", question_id=question_id))
    else:
        flash("表单验证失败！")
        return redirect(url_for("qa.question_detail", question_id=question_id))


@bp.route("/search")
def search():
    seek = request.args.get("seek")
    questions = QuestionModel.query.filter(
        or_(QuestionModel.title.contains(seek), QuestionModel.content.contains(seek))).order_by(db.text("-create_time"))
    return render_template("index.html", questions=questions)

blueprints/user.py
from flask import (Blueprint, render_template, request, redirect, url_for, jsonify,session,flash)
from exts import mail, db
from flask_mail import Message
from models import EmailCaptchaModel, UserModel
import string
import random
from datetime import datetime
from .forms import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint("user", __name__, url_prefix="/user")



@bp.route("/logout")
def logout():
    session.clear() #退出登录
    return redirect(url_for("user.login"))

@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password,password):
                session['user_id']=user.id
                return redirect("/")
            else:
                flash("密码错误")
                return redirect(url_for("user.login"))
        else:
            flash("格式错误")
            return redirect(url_for("user.login"))

@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data

            hash_password = generate_password_hash(password)
            user = UserModel(email=email, username=username, password=hash_password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))


@bp.route("/captcha", methods=['POST'])
def get_captcha():
    email = request.form.get("email")
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters, 4))
    if email:
        message = Message(
            subject="邮箱测试",
            recipients=[email],
            body=f"您的验证码是：{captcha},不要告诉别人"
        )

        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        # code:200 正常请求
        return jsonify({"code": 200})
    else:
        # code:400 客户端错误
        return jsonify({"code": 400, "message": "请先输入邮箱"})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap.4.6.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
  {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/">果园小墙</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for("qa.public_question") }}">发布动态</a>
        </li>
        <li class="nav-item ml-2">
          <form class="form-inline my-2 my-lg-0" method="get" action="{{ url_for('qa.search') }}">
            <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="seek">
            <button class="btn btn-outline-secondary" type="submit">搜索</button>
          </form>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if user %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">{{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
<div class="container">{% block body %}{% endblock %}</div>
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}
  动态详情
{% endblock %}


{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/detail.css') }}">
{% endblock %}


{% block body %}
  <div class="row" style="margin-top: 20px">
    <div class="col"></div>
    <div class="col-8 shadow p-2 mb-3 bg-white rounded" style="background-color: white">
      <h3 class="title">{{ question.title }}</h3>
      <p class="question_imf">
        <span style="padding-right:10px ">by:{{ question.author.username }}</span>
        <span>{{ question.create_time }}</span>
      </p>
      <hr>
      <p class="q-content">{{ question.content }}</p>
      <hr>
      <h4 class="comment-title">评论（{{ question.answer|length }}）:</h4>
      <form action="{{ url_for('qa.answer',question_id=question.id) }}" method="post">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="请输入评论！" name="content">
          <button class="btn btn-outline-secondary" type="submit">提交</button>
        </div>
        <div>
          {% for message in get_flashed_messages() %}
            <div class="form-group">
              <div class="text-danger">{{ message }}</div>
            </div>
          {% endfor %}
        </div>
      </form>
      {% for ans in question.answer %}
        <ul class="comment-group">
          <div class="user-info">
            <span class="username">{{ans.author.username}}</span>
            <span class="create-time">{{ans.create_time}}</span>
          </div>
          <p class="cpomment-content">{{ans.content}}</p>
        </ul>
        <hr>
      {% endfor %}
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}果园小墙{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
  <div class="row">
    <div class="col"></div>
    <div class="col-8">
      {% for question in questions %}
      <div class="shadow p-2 mb-3 bg-white rounded kuang">
          <div class="title"><a href="{{url_for('qa.question_detail',question_id=question.id)}}">{{question.title}}</a></div>
          <div class="content ">{{question.content}}</div>
          <div class="author">{{question.author.username}}</div>
          <div class="time">{{question.create_time}}</div>
          </div>
        {% endfor %}
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}果园小墙—登录{% endblock %}

{% block head %}

{% endblock %}

{% block body %}
  <div class="row mt-4">
    <div class="col"></div>
    <div class="col">
      <form action="{{ url_for("user.login") }}" method="POST">
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">密码</label>
          <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="form-group form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>

        {% for message in get_flashed_messages() %}
          <div class="form-group">
            <div class="text-danger">{{ message }}</div>
          </div>
        {% endfor %}

        <div class="form-group">
          <button type="submit" class="btn btn-primary btn-block">登录</button>
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/public_question.html
{% extends "base.html" %}

{% block title %}发布动态{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px;">
    <div class="col"></div>
    <div class="col-8">
      <h1 style="text-align: center">发布动态</h1>
      <form action="{{ url_for('qa.public_question') }}" method="post">
        <div class="form-group">
          <input type="text" name="title" class="form-control" placeholder="请输入标题">
        </div>
        <div class="form-group">
          <textarea name="content" id="" class="form-control" cols="40" rows="10" placeholder="请输入内容"></textarea>
        </div>
        <div class="form-group" style="text-align: center" size="large">
          <button class="btn btn-dark btn-lg btn-block" type="submit">发布</button>
        </div>
      </form>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}果园小墙—注册{% endblock %}

{% block head %}
  <script src="{{ url_for('static',filename='jquery/jquery-3.6.0.min.js') }}"></script>
  <script src="{{ url_for('static',filename='js/register.js') }}"></script>
{% endblock %}

{% block body %}
  <div class="row mt-4">
    <div class="col"></div>
    <div class="col">
      <form method="POST" action="{{ url_for('user.register') }}">
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">验证码</label>
          <div class="input-group">
            <input type="text" class="form-control" name="captcha">
            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">用户名</label>
          <input type="text" class="form-control" name="username">
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">密码</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">确认密码</label>
          <input type="password" class="form-control" name="password_comfirm">
        </div>
        <div class="form-group form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary btn-block">立即注册</button>
      </form>
    </div>
    <div class="col"></div>
  </div>
{% endblock %}